export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
export const CART_LIST_FAIL = 'CART_LIST_FAIL';

export const CART_CREATE_REQUEST = 'CART_CREATE_REQUEST';
export const CART_CREATE_SUCCESS = 'CART_CREATE_SUCCESS';
export const CART_CREATE_FAIL = 'CART_CREATE_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_LIST_MY_RESET = 'CART_LIST_MY_RESET';

export const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST';
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
export const CART_DELETE_FAIL = 'CART_DELETE_FAIL';

export const CART_CLEAR_SUCCESS = 'CART_CLEAR_SUCCESS';

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';
export const CART_UPDATE_RESET = 'CART_UPDATE_RESET';

export const CART_ADD_PRODUCT_ORDER_REQUEST = 'CART_ADD_PRODUCT_ORDER_REQUEST';
export const CART_ADD_PRODUCT_ORDER_SUCCESS = 'CART_ADD_PRODUCT_ORDER_SUCCESS';
export const CART_SAVE_SHIPPING_ADDRESS_ORDER = 'CART_SAVE_SHIPPING_ADDRESS_ORDER';
export const CART_ADD_PRODUCT_ORDER_FAIL = 'CART_ADD_PRODUCT_ORDER_FAIL';
export const CART_ORDER_SHIPPING_ADDRESS = 'CART_ORDER_SHIPPING_ADDRESS';
export const CART_ORDER_RESET = 'CART_ORDER_RESET';
